apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name:
spec:
  runPolicy: Serial
  source:
      git:
        ref: master
        uri: https://github.com/rnuxip/tests/
      type: Git
  strategy:
      sourceStrategy: dockerStrategy
      type: Source
  output:
    to:
      kind: simple-web-docker:latest
      name:
  triggers:
    - type: ConfigChange
